insert into property_classification_mart.place_keyword_mapping (
    keyword_id,
    keyword,
    keyword_clean,
    match_type,
    place_domain,
    mapped_category,
    mapped_subcategory,
    mapped_detail_level_3,
    keyword_role,
    weight,
    priority,
    active_flag,
    notes
)
select
    seed.keyword_id,
    seed.keyword,
    seed.keyword_clean,
    seed.match_type,
    seed.place_domain,
    seed.mapped_category,
    seed.mapped_subcategory,
    seed.mapped_detail_level_3,
    seed.keyword_role,
    seed.weight,
    seed.priority,
    seed.active_flag,
    seed.notes
from (
    values
        ('restaurant_italian_001', 'italian', 'italian', 'contains', 'restaurants', 'restaurants', 'italian', '', 'cuisine', 8, 10, true, 'Strong Italian cuisine signal'),
        ('restaurant_french_001', 'french', 'french', 'contains', 'restaurants', 'restaurants', 'french', '', 'cuisine', 8, 10, true, 'Strong French cuisine signal'),
        ('restaurant_american_001', 'new american', 'new american', 'phrase', 'restaurants', 'restaurants', 'american', 'new_american', 'cuisine', 10, 5, true, 'Strong New American cuisine signal'),
        ('restaurant_american_002', 'american', 'american', 'contains', 'restaurants', 'restaurants', 'american', '', 'cuisine', 6, 20, true, 'Broad American cuisine signal'),
        ('restaurant_american_003', 'contemporary', 'contemporary', 'contains', 'restaurants', 'restaurants', 'american', 'fine_dining', 'experience', 5, 25, true, 'Contemporary cuisine often overlaps with modern American fine dining'),
        ('restaurant_american_004', 'farm to table', 'farm to table', 'phrase', 'restaurants', 'restaurants', 'american', 'farm_to_table', 'experience', 8, 10, true, 'Specific farm-to-table signal'),
        ('restaurant_american_005', 'comfort food', 'comfort food', 'phrase', 'restaurants', 'restaurants', 'american', 'comfort_food', 'type', 7, 15, true, 'Strong comfort-food signal'),
        ('restaurant_american_006', 'burger', 'burger', 'contains', 'restaurants', 'restaurants', 'american', 'burger', 'product', 7, 15, true, 'Burger signal'),
        ('restaurant_american_007', 'burgers', 'burgers', 'contains', 'restaurants', 'restaurants', 'american', 'burger', 'product', 7, 15, true, 'Burgers signal'),
        ('restaurant_american_008', 'diner', 'diner', 'contains', 'restaurants', 'restaurants', 'american', 'diner', 'format', 7, 15, true, 'Diner signal'),
        ('restaurant_detail_001', 'fine dining', 'fine dining', 'phrase', 'restaurants', 'restaurants', '__any__', 'fine_dining', 'experience', 7, 15, true, 'Generic fine-dining detail signal'),
        ('restaurant_detail_002', 'small plates', 'small plates', 'phrase', 'restaurants', 'restaurants', '__any__', 'small_plates', 'format', 7, 15, true, 'Generic small-plates detail signal'),
        ('restaurant_detail_003', 'bar food', 'bar food', 'phrase', 'restaurants', 'restaurants', '__any__', 'bar_food', 'type', 6, 20, true, 'Generic bar-food detail signal'),
        ('restaurant_detail_004', 'gastropub', 'gastropub', 'contains', 'restaurants', 'restaurants', '__any__', 'gastropub', 'type', 7, 15, true, 'Generic gastropub detail signal'),
        ('restaurant_steakhouse_001', 'steakhouse', 'steakhouse', 'contains', 'restaurants', 'restaurants', 'steakhouse', '', 'type', 10, 5, true, 'Highly specific steakhouse signal'),
        ('restaurant_japanese_001', 'japanese', 'japanese', 'contains', 'restaurants', 'restaurants', 'japanese', '', 'cuisine', 7, 15, true, 'Broad Japanese cuisine signal'),
        ('restaurant_japanese_002', 'sushi', 'sushi', 'contains', 'restaurants', 'restaurants', 'japanese', 'sushi', 'cuisine', 9, 5, true, 'Highly specific sushi signal'),
        ('restaurant_japanese_003', 'omakase', 'omakase', 'contains', 'restaurants', 'restaurants', 'japanese', 'omakase', 'experience', 10, 5, true, 'Highly specific omakase signal'),
        ('restaurant_japanese_004', 'ramen', 'ramen', 'contains', 'restaurants', 'restaurants', 'japanese', 'ramen', 'product', 10, 5, true, 'Highly specific ramen signal'),
        ('restaurant_japanese_005', 'kaiseki', 'kaiseki', 'contains', 'restaurants', 'restaurants', 'japanese', 'kaiseki', 'experience', 9, 10, true, 'Kaiseki signal'),
        ('restaurant_japanese_006', 'temaki', 'temaki', 'contains', 'restaurants', 'restaurants', 'japanese', 'temaki', 'product', 8, 15, true, 'Temaki signal'),
        ('restaurant_japanese_007', 'nigiri', 'nigiri', 'contains', 'restaurants', 'restaurants', 'japanese', 'sushi', 'product', 8, 15, true, 'Nigiri signal'),
        ('restaurant_japanese_008', 'chirashi', 'chirashi', 'contains', 'restaurants', 'restaurants', 'japanese', 'chirashi', 'product', 8, 15, true, 'Chirashi signal'),
        ('restaurant_chinese_001', 'chinese', 'chinese', 'contains', 'restaurants', 'restaurants', 'chinese', '', 'cuisine', 8, 10, true, 'Broad Chinese cuisine signal'),
        ('restaurant_chinese_002', 'dim sum', 'dim sum', 'phrase', 'restaurants', 'restaurants', 'chinese', 'dim_sum', 'product', 10, 5, true, 'Highly specific dim sum signal'),
        ('restaurant_chinese_003', 'dumpling', 'dumpling', 'contains', 'restaurants', 'restaurants', 'chinese', 'dumplings', 'product', 8, 10, true, 'Strong dumpling signal'),
        ('restaurant_chinese_004', 'soup dumplings', 'soup dumplings', 'phrase', 'restaurants', 'restaurants', 'chinese', 'dumplings', 'product', 9, 10, true, 'Soup dumpling signal'),
        ('restaurant_chinese_005', 'shanghai', 'shanghai', 'contains', 'restaurants', 'restaurants', 'chinese', 'shanghai', 'cuisine', 8, 15, true, 'Shanghai cuisine signal'),
        ('restaurant_bbq_001', 'bbq', 'bbq', 'contains', 'restaurants', 'restaurants', 'barbecue', '', 'cuisine', 8, 10, true, 'Common barbecue abbreviation'),
        ('restaurant_bbq_002', 'barbecue', 'barbecue', 'contains', 'restaurants', 'restaurants', 'barbecue', '', 'cuisine', 8, 10, true, 'Strong barbecue signal'),
        ('restaurant_mexican_001', 'mexican', 'mexican', 'contains', 'restaurants', 'restaurants', 'mexican', '', 'cuisine', 8, 10, true, 'Strong Mexican cuisine signal'),
        ('restaurant_mexican_002', 'taqueria', 'taqueria', 'contains', 'restaurants', 'restaurants', 'mexican', 'tacos', 'type', 8, 15, true, 'Taqueria signal'),
        ('restaurant_mexican_003', 'tacos', 'tacos', 'contains', 'restaurants', 'restaurants', 'mexican', 'tacos', 'product', 8, 15, true, 'Taco signal'),
        ('restaurant_mexican_004', 'tamal', 'tamal', 'contains', 'restaurants', 'restaurants', 'mexican', 'tamales', 'product', 8, 15, true, 'Tamal signal'),
        ('restaurant_mexican_005', 'tamales', 'tamales', 'contains', 'restaurants', 'restaurants', 'mexican', 'tamales', 'product', 8, 15, true, 'Tamales signal'),
        ('restaurant_indian_001', 'indian', 'indian', 'contains', 'restaurants', 'restaurants', 'indian', '', 'cuisine', 8, 10, true, 'Strong Indian cuisine signal'),
        ('restaurant_korean_001', 'korean', 'korean', 'contains', 'restaurants', 'restaurants', 'korean', '', 'cuisine', 8, 10, true, 'Strong Korean cuisine signal'),
        ('restaurant_vietnamese_001', 'vietnamese', 'vietnamese', 'contains', 'restaurants', 'restaurants', 'vietnamese', '', 'cuisine', 8, 10, true, 'Strong Vietnamese cuisine signal'),
        ('restaurant_spanish_001', 'spanish', 'spanish', 'contains', 'restaurants', 'restaurants', 'spanish', '', 'cuisine', 8, 10, true, 'Strong Spanish cuisine signal'),
        ('restaurant_spanish_002', 'tapas', 'tapas', 'contains', 'restaurants', 'restaurants', 'spanish', 'tapas', 'type', 8, 10, true, 'Tapas signal'),
        ('restaurant_spanish_003', 'pintxos', 'pintxos', 'contains', 'restaurants', 'restaurants', 'spanish', 'tapas', 'type', 8, 15, true, 'Pintxos signal'),
        ('restaurant_middle_eastern_001', 'middle east', 'middle east', 'phrase', 'restaurants', 'restaurants', 'middle_eastern', '', 'cuisine', 7, 10, true, 'Middle East phrase signal'),
        ('restaurant_middle_eastern_002', 'middle eastern', 'middle eastern', 'phrase', 'restaurants', 'restaurants', 'middle_eastern', '', 'cuisine', 8, 10, true, 'Strong Middle Eastern cuisine signal'),
        ('restaurant_middle_eastern_003', 'turkish', 'turkish', 'contains', 'restaurants', 'restaurants', 'middle_eastern', 'turkish', 'cuisine', 7, 15, true, 'Turkish cuisine signal'),
        ('restaurant_middle_eastern_004', 'israeli', 'israeli', 'contains', 'restaurants', 'restaurants', 'middle_eastern', 'israeli', 'cuisine', 7, 15, true, 'Israeli cuisine signal'),
        ('restaurant_middle_eastern_005', 'egyptian', 'egyptian', 'contains', 'restaurants', 'restaurants', 'middle_eastern', 'egyptian', 'cuisine', 7, 15, true, 'Egyptian cuisine signal'),
        ('restaurant_mediterranean_001', 'mediterranean', 'mediterranean', 'contains', 'restaurants', 'restaurants', 'mediterranean', '', 'cuisine', 8, 10, true, 'Mediterranean cuisine signal'),
        ('restaurant_greek_001', 'greek', 'greek', 'contains', 'restaurants', 'restaurants', 'greek', '', 'cuisine', 8, 10, true, 'Strong Greek cuisine signal'),
        ('restaurant_caribbean_001', 'caribbean', 'caribbean', 'contains', 'restaurants', 'restaurants', 'caribbean', '', 'cuisine', 8, 10, true, 'Strong Caribbean cuisine signal'),
        ('restaurant_caribbean_002', 'cuban', 'cuban', 'contains', 'restaurants', 'restaurants', 'caribbean', 'cuban', 'cuisine', 7, 15, true, 'Cuban cuisine signal'),
        ('restaurant_caribbean_003', 'trinidadian', 'trinidadian', 'contains', 'restaurants', 'restaurants', 'caribbean', 'trinidadian', 'cuisine', 9, 10, true, 'Trinidadian cuisine signal'),
        ('restaurant_caribbean_004', 'roti', 'roti', 'contains', 'restaurants', 'restaurants', 'caribbean', 'roti', 'product', 8, 15, true, 'Roti signal'),
        ('restaurant_caribbean_005', 'doubles', 'doubles', 'contains', 'restaurants', 'restaurants', 'caribbean', 'trinidadian', 'product', 9, 10, true, 'Trinidadian doubles signal'),
        ('restaurant_caribbean_006', 'pholorie', 'pholorie', 'contains', 'restaurants', 'restaurants', 'caribbean', 'trinidadian', 'product', 9, 10, true, 'Pholorie signal'),
        ('restaurant_caribbean_007', 'saheena', 'saheena', 'contains', 'restaurants', 'restaurants', 'caribbean', 'trinidadian', 'product', 9, 10, true, 'Saheena signal'),
        ('restaurant_caribbean_008', 'aloo pie', 'aloo pie', 'phrase', 'restaurants', 'restaurants', 'caribbean', 'trinidadian', 'product', 9, 10, true, 'Aloo pie signal'),
        ('restaurant_peruvian_001', 'peruvian', 'peruvian', 'contains', 'restaurants', 'restaurants', 'peruvian', '', 'cuisine', 8, 10, true, 'Peruvian cuisine signal'),
        ('restaurant_filipino_001', 'filipino', 'filipino', 'contains', 'restaurants', 'restaurants', 'filipino', '', 'cuisine', 8, 10, true, 'Filipino cuisine signal'),
        ('restaurant_malaysian_001', 'malaysian', 'malaysian', 'contains', 'restaurants', 'restaurants', 'malaysian', '', 'cuisine', 8, 10, true, 'Malaysian cuisine signal'),
        ('restaurant_thai_001', 'thai', 'thai', 'contains', 'restaurants', 'restaurants', 'thai', '', 'cuisine', 8, 10, true, 'Thai cuisine signal'),
        ('restaurant_taiwanese_001', 'taiwanese', 'taiwanese', 'contains', 'restaurants', 'restaurants', 'taiwanese', '', 'cuisine', 8, 10, true, 'Taiwanese cuisine signal'),
        ('restaurant_african_001', 'west african', 'west african', 'phrase', 'restaurants', 'restaurants', 'african', 'west_african', 'cuisine', 8, 10, true, 'West African cuisine signal'),
        ('restaurant_african_002', 'african', 'african', 'contains', 'restaurants', 'restaurants', 'african', '', 'cuisine', 7, 20, true, 'Broad African cuisine signal'),
        ('restaurant_african_003', 'nigerian', 'nigerian', 'contains', 'restaurants', 'restaurants', 'african', 'nigerian', 'cuisine', 9, 10, true, 'Nigerian cuisine signal'),
        ('restaurant_sri_lankan_001', 'sri lankan', 'sri lankan', 'phrase', 'restaurants', 'restaurants', 'sri_lankan', '', 'cuisine', 8, 10, true, 'Sri Lankan cuisine signal'),
        ('restaurant_georgian_001', 'georgian', 'georgian', 'contains', 'restaurants', 'restaurants', 'georgian', '', 'cuisine', 8, 10, true, 'Georgian cuisine signal'),
        ('restaurant_german_001', 'austrian', 'austrian', 'contains', 'restaurants', 'restaurants', 'german_austrian', 'austrian', 'cuisine', 7, 15, true, 'Austrian cuisine signal'),
        ('restaurant_german_002', 'german', 'german', 'contains', 'restaurants', 'restaurants', 'german_austrian', 'german', 'cuisine', 7, 15, true, 'German cuisine signal'),
        ('restaurant_scandinavian_001', 'scandinavian', 'scandinavian', 'contains', 'restaurants', 'restaurants', 'scandinavian', '', 'cuisine', 8, 10, true, 'Scandinavian cuisine signal'),
        ('restaurant_eastern_european_001', 'eastern european', 'eastern european', 'phrase', 'restaurants', 'restaurants', 'eastern_european', '', 'cuisine', 8, 10, true, 'Eastern European cuisine signal'),
        ('restaurant_central_asian_001', 'central asian', 'central asian', 'phrase', 'restaurants', 'restaurants', 'central_asian', '', 'cuisine', 8, 10, true, 'Central Asian cuisine signal'),
        ('restaurant_central_asian_002', 'tibetan', 'tibetan', 'contains', 'restaurants', 'restaurants', 'central_asian', 'tibetan', 'cuisine', 7, 15, true, 'Tibetan cuisine signal'),
        ('restaurant_pakistani_001', 'pakistani', 'pakistani', 'contains', 'restaurants', 'restaurants', 'pakistani', '', 'cuisine', 8, 10, true, 'Pakistani cuisine signal'),
        ('restaurant_pakistani_002', 'indo pak', 'indo pak', 'phrase', 'restaurants', 'restaurants', 'pakistani', 'indo_pak', 'cuisine', 7, 15, true, 'Indo-Pak cuisine signal'),
        ('restaurant_deli_001', 'deli', 'deli', 'contains', 'restaurants', 'restaurants', 'deli', '', 'type', 7, 15, true, 'Deli signal'),
        ('restaurant_deli_002', 'kosher', 'kosher', 'contains', 'restaurants', 'restaurants', 'deli', 'kosher', 'type', 7, 15, true, 'Kosher deli signal'),
        ('restaurant_southern_001', 'southern soul', 'southern soul', 'phrase', 'restaurants', 'restaurants', 'southern_soul', '', 'cuisine', 8, 10, true, 'Southern and soul food cuisine signal'),
        ('restaurant_southern_002', 'southern', 'southern', 'contains', 'restaurants', 'restaurants', 'southern_soul', '', 'cuisine', 7, 15, true, 'Southern cuisine signal'),
        ('restaurant_southern_003', 'soul', 'soul', 'contains', 'restaurants', 'restaurants', 'southern_soul', 'soul_food', 'cuisine', 7, 15, true, 'Soul food signal'),
        ('restaurant_southern_004', 'cajun', 'cajun', 'contains', 'restaurants', 'restaurants', 'southern_soul', 'cajun_creole', 'cuisine', 8, 15, true, 'Cajun signal'),
        ('restaurant_southern_005', 'creole', 'creole', 'contains', 'restaurants', 'restaurants', 'southern_soul', 'cajun_creole', 'cuisine', 8, 15, true, 'Creole signal'),
        ('restaurant_southern_006', 'new orleans', 'new orleans', 'phrase', 'restaurants', 'restaurants', 'southern_soul', 'cajun_creole', 'cuisine', 8, 15, true, 'New Orleans signal'),
        ('restaurant_southern_007', 'gumbo', 'gumbo', 'contains', 'restaurants', 'restaurants', 'southern_soul', 'cajun_creole', 'product', 8, 15, true, 'Gumbo signal'),
        ('restaurant_southern_008', 'po boys', 'po boys', 'phrase', 'restaurants', 'restaurants', 'southern_soul', 'sandwiches', 'product', 8, 15, true, 'Po-boy signal'),
        ('restaurant_latin_001', 'latin american', 'latin american', 'phrase', 'restaurants', 'restaurants', 'latin_american', '', 'cuisine', 8, 10, true, 'Latin American cuisine signal'),
        ('restaurant_latin_002', 'south american', 'south american', 'phrase', 'restaurants', 'restaurants', 'latin_american', 'south_american', 'cuisine', 7, 15, true, 'South American cuisine signal'),
        ('restaurant_latin_003', 'colombian', 'colombian', 'contains', 'restaurants', 'restaurants', 'latin_american', 'colombian', 'cuisine', 8, 10, true, 'Colombian cuisine signal'),
        ('restaurant_vegetarian_001', 'vegetarian', 'vegetarian', 'contains', 'restaurants', 'restaurants', 'vegetarian', '', 'type', 8, 10, true, 'Vegetarian restaurant signal'),
        ('restaurant_vegetarian_002', 'vegan', 'vegan', 'contains', 'restaurants', 'restaurants', 'vegetarian', 'vegan', 'type', 8, 10, true, 'Vegan restaurant signal'),
        ('restaurant_seafood_001', 'seafood', 'seafood', 'contains', 'restaurants', 'restaurants', 'seafood', '', 'type', 7, 15, true, 'Seafood restaurant signal'),
        ('restaurant_cafe_001', 'cafe', 'cafe', 'contains', 'restaurants', 'restaurants', 'cafe', '', 'format', 6, 20, true, 'Cafe-style restaurant signal'),
        ('restaurant_pizza_001', 'pizza', 'pizza', 'contains', 'restaurants', 'restaurants', 'pizza', 'general_pizza', 'type', 9, 5, true, 'Strong pizza signal'),
        ('restaurant_pizza_002', 'slice', 'slice', 'contains', 'restaurants', 'restaurants', 'pizza', 'slice_shop', 'format', 6, 15, true, 'Supporting slice-shop signal'),
        ('restaurant_pizza_003', 'pizzaiolo', 'pizzaiolo', 'contains', 'restaurants', 'restaurants', 'pizza', 'general_pizza', 'type', 8, 15, true, 'Pizzaiolo signal'),
        ('restaurant_pizza_004', 'neapolitan pies', 'neapolitan pies', 'phrase', 'restaurants', 'restaurants', 'pizza', 'neapolitan', 'type', 8, 15, true, 'Neapolitan pizza signal'),
        ('restaurant_bakery_001', 'bakery', 'bakery', 'contains', 'restaurants', 'restaurants', 'bakery', 'bakery', 'type', 8, 10, true, 'Strong bakery signal within restaurant bucket'),
        ('restaurant_bakery_002', 'pastry', 'pastry', 'contains', 'restaurants', 'restaurants', 'bakery', 'pastry', 'product', 6, 15, true, 'Supporting pastry signal'),
        ('restaurant_bagels_001', 'bagel', 'bagel', 'contains', 'restaurants', 'restaurants', 'bagels', '', 'type', 8, 10, true, 'Bagel signal'),
        ('restaurant_bagels_002', 'bagels', 'bagels', 'contains', 'restaurants', 'restaurants', 'bagels', '', 'type', 8, 10, true, 'Bagels signal'),
        ('restaurant_bagels_003', 'montreal style', 'montreal style', 'phrase', 'restaurants', 'restaurants', 'bagels', 'montreal_style', 'type', 8, 15, true, 'Montreal-style bagel signal'),
        ('restaurant_hot_dogs_001', 'hot dog', 'hot dog', 'phrase', 'restaurants', 'restaurants', 'hot_dogs', '', 'type', 8, 10, true, 'Hot dog signal'),
        ('restaurant_hot_dogs_002', 'hot dogs', 'hot dogs', 'phrase', 'restaurants', 'restaurants', 'hot_dogs', '', 'type', 8, 10, true, 'Hot dogs signal'),
        ('restaurant_hot_dogs_003', 'wieners', 'wieners', 'contains', 'restaurants', 'restaurants', 'hot_dogs', '', 'type', 8, 15, true, 'Wiener signal'),
        ('restaurant_fast_casual_001', 'fast casual', 'fast casual', 'phrase', 'restaurants', 'restaurants', 'restaurants', 'fast_casual', 'format', 7, 15, true, 'Fast-casual signal'),
        ('restaurant_health_food_001', 'health food', 'health food', 'phrase', 'restaurants', 'restaurants', 'restaurants', 'health_food', 'type', 7, 15, true, 'Health-food signal'),
        ('restaurant_liquor_shop_001', 'wine shop', 'wine shop', 'phrase', 'shopping', 'shopping', 'shopping', 'liquor_store', 'type', 8, 15, true, 'Wine shop signal'),
        ('restaurant_liquor_shop_002', 'bottle shop', 'bottle shop', 'phrase', 'shopping', 'shopping', 'shopping', 'liquor_store', 'type', 8, 15, true, 'Bottle shop signal'),
        ('restaurant_liquor_shop_003', 'spirits', 'spirits', 'contains', 'shopping', 'shopping', 'shopping', 'liquor_store', 'type', 6, 20, true, 'Spirits shop signal')
) as seed(
    keyword_id,
    keyword,
    keyword_clean,
    match_type,
    place_domain,
    mapped_category,
    mapped_subcategory,
    mapped_detail_level_3,
    keyword_role,
    weight,
    priority,
    active_flag,
    notes
)
where not exists (
    select 1
    from property_classification_mart.place_keyword_mapping existing
    where existing.keyword_id = seed.keyword_id
);
